print("note:(1) pokemon's name should be in small letters")
print("     (2) this poketab is restricted only till jhoto league")
print("after you repeat to search more than 1 time, you should exit after pressing anything on the board and press enter")
a=str(input("enter the name of pokemon you wish to know about:"))
print("info::")
if a=='chikorita':
    print("1.chikorita")
    print("height:88.9cm")
    print("weight:6.4kg")
    print("grass type pokemon ")
    print(" evovles to:bayleef")
elif a=='bayleef':
    print("2.bayleef")
    print("height:1.19m")
    print("weight:16kg")
    print("grass type pokemon")
    print("evolves to meganium")
elif a=='meganium':
    print("3.megnium")
    print("height:1.8m")
    print("weght:100.5kg")
    print("grass type pokemon")
    print("dosen't evolve")
elif a=='cyndaquill':
    print("4.cydaquill")
    print("height:50.8cm")
    print("weight:7.9kg")
    print("fire type pokemon")
    print("evolves to quillava")
elif a=='quilava':
    print("5.quilava")
    print("height:88.9cm")
    print("weight:19kg")
    print("fire type pokemon")
    print("evovles to typhlosion")
elif a=='typhlosion':
    print("6.typhosion")
    print("height:1.7m")
    print("weight:8kg")
    print("fire type pokemon")
    print("dosn't evovle")
elif a=='totodile':
    print("7.totodile")
    print("height:61m")
    print("weight:9.5kg")
    print("water type pokemon")
    print("evolves to croconaw")
elif a=='croconaw':
    print("8.croconaw")
    print("height:1.9m")
    print("weight:25kg")
    print("water type pokemon")
    print("evolves to feraligator")
elif a=='feraligator':
    print("9.feraligator")
    print("height:2.31m")
    print("weight:89kg")
    print("water type pokemon")
    print("dosn't evolves")
elif a=='senteret':
    print("10.senteret")
    print("height:78.7cm")
    print("weight:6kg"),sdv
    print("normal type pokemon")
    print("evolves to furret")
elif a=='furret':
    print("11.furret")
    print("height:1.8m")
    print("weight:32kg")
    print("normal type pokemon")
    print("evolves to hoothoot")
elif a=='hoothoot':
    print("12.hoothoot")
    print("height:71.1cm")
    print("weight:21kg")
    print("normal type pokemon")
    print("evolves to noctowl")
elif a=='noctowl':
    print("13.noctowl")
    print("height:1.6 m")
    print("weight:41 kg")
    print("normal type pokemon")
    print("dosen't evolve")
elif a=='ledyba':
    print("14.Ledyba")
    print("height:99.1 cm")
    print("weight:11 kg")
    print("bug and flying type pokemon")
    print("evolves to ledian")
elif a=='ledian':
    print("15.Ledian")
    print("height:1.4 m")
    print("weight:36 kg ")
    print("bug and flying type pokemon")
    print(" dosen't evolve")
elif a=='spinarak':
    print("16.Spinarak")
    print("height:50.8cm")
    print("weight:8.5 kg")
    print("bug and poison type pokemon")
    print("evolves to ariados")
elif a=='ariados':
    print("17.Ariados")
    print("height:1.09 m")
    print("weight:34 kg")
    print("bug and poison type pokemon")
    print("dosen't evolve")
elif a=='crobat':
    print("18.crobat")
    print("height:1.8 m")
    print("weight:75 kg")
    print("poison and flying type pokemon")
    print("dosen't evolve")
elif a=='chinchou':
    print("19.Chinchou")
    print("height:50.8")
    print("weight:12 kg")
    print("electric and water type pokemon")
    print("evolves to lanturn")
elif a=='lanturn':
    print("20. lanturn")
    print("height:1.2 m")
    print("weight:22.5 kg")
    print("electric and water type pokemon")
    print("dosen't evolve")
elif a=='pichu':
    print("21.pichu")
    print("height:0.3m")
    print("weight:2 kg")
    print("electric type pokemon")
    print("evolves to pikachu")
elif a=='cleffa':
    print("22.cleffa")
    print("height:0.3m")
    print("weight:3 kg")
    print("fairy type pokemon")
    print("evolves to clefairy")
elif a=='igglybuff':
    print("23.igglybuff")
    print("height:0.3m")
    print("weight:1 kg")
    print("fairy and normal type pokemon")
    print("evolves to jigglypuff")
elif a=='togepi':
    print("24.togepi")
    print("height:0.3m")
    print("weight:1kg")
    print("fairy type pokemon")
    print("evolves to togetic")
elif a=='togetic':
     print("25.togetic")
     print("height:0.6 m")
     print("weight:3.2 kg")
     print("fairy and flying type pokemon")
     print("evolves to togekiss")
elif a=='natu':
     print("26.natu")
     print("height:0.2 m")
     print("weight:2 kg")
     print("psichic and flying type pokemon")
     print("evolves to xatu ")
elif a=='xatu':
     print("27.xatu")
     print("height:1.5 m")
     print("weight:15 kg")
     print("psychic and flying type pokemon")
     print("dosen't evolve")
elif a=='mareep':
     print("28.mareep")
     print("height:0.6 m")
     print("weight:7.8 kg")
     print("electric type pokemon")
     print("evolves to flaffy")
elif a=='flaafy':
     print("29.flaafy")
     print("height:78.7 cm")
     print("weight:13 kg")
     print("electric type pokemon")
     print("evolves to ampharos")
elif a=='ampharos':
     print("30.ampharos")
     print("height:1.4 m")
     print("weight:61.5 kg ")
     print("electric type pokemon")
     print("dosen't evolve")
elif a=='bellossom':
     print("31.bellossom")
     print("height:40.6 cm")
     print("weight:5.8 kg")
     print("grass type pokemon")
     print("dosen't evolve")
elif a=='marill':
     print("32.marill")
     print("height:40.6 cm")
     print("weight:8.5 kg")
     print("water type pokemon")
     print("evolves to azumarill")
elif a=='azumarill':
     print("33.azumarill")
     print("height:78.5 cm")
     print("weight:28 kg")
     print("water type pokemon")
     print("dosen't evolve")
elif a=='politoed':
     print("34.politoed")
     print("height:1.09m")
     print("weight:34 kg")
     print("water type pokemon")
     print("dosen't evolve")
elif a=='sudowoodo':
     print("35.sudowoodo")
     print("height:1.19 m")
     print("weight:38 kg")
     print("rock type pokemon")
     print("dosen't evolve")
elif a=='hoppip':
    print("36.hoppip")
    print("height:40.6 cm")
    print("weight:499 g")
    print("flying and grass type pokemon")
    print("evolves to skiploom")
elif a=='skiploom':
    print("37.skiploom")
    print("height:61 cm")
    print("weight:998 g")
    print("flying and grass type pokemon")
    print("evolves to jumpluff")
elif a=='jumpluff':
    print("38.jumpluff")
    print("height:78.7 cm")
    print("weight:3 kg")
    print("flying and grass type pokemon")
    print("dosen't evolve")    
elif a=='aipom':
    print("39.aipom")
    print("height:78.7")
    print("weight:12 kg ")
    print("normal type pokemon")
    print("evolves to ambipom")
elif a=='sunkern':
    print("40.sunkern")
    print("height:30.5cm")
    print("weight:1.8 kg")
    print("grass type pokemon")
    print("evolves to sunflora")
elif a=='sunflora':
    print("41.sunflora")
    print("height:78.7 cm")
    print("weight:8.5 kg")
    print("grass type pokemon")
    print("dosen't evolve")
elif a=='yanma':
    print("42.yanma")
    print("height:1.19m")
    print("weight:38 kg")
    print("flying and bug type pokemon")
    print("evolves to yanmega")
elif a=='wooper':
    print("43.wooper")
    print("height:40.6 cm ")
    print("weight:8.5 kg ")
    print("ground and water type pokemon")
    print("evolves to quagsire")
elif a=='quagsire':
    print("44.quagsire")
    print("height:1.4 m")
    print("weight:75 kg")
    print("ground and water type pokemon")
    print("dosen't evolve")
elif a=='espeon':
    print("45.espeon")
    print("height:88.9 cm")
    print("weight:26 kg")
    print("psychic type pokemon")
    print("dosen't evolve")
elif a=='umbreon':
    print("46.umbreon")
    print("height:99.1 cm")
    print("weight:27 kg")
    print("dark type pokemon")
    print("dosen't evolve")
elif a=='murkrow':
    print("47.murkrow")
    print("height:50.8 cm")
    print("weight:2.1 kg")
    print("dark and flying type pokemon")
    print("evolves to honchkrow")
elif a=='slowking':
    print("48.slowking")
    print("height:2.01 m")
    print("weight:80 kg")
    print("psychic and water type pokemon")
    print("dosen't evolve")
elif a=='misdreavus':
    print("49.misdreavus")
    print("height:71.1 cm")
    print("weight:998 g")       
    print("ghost type pokemon")
    print("evolves to mismagius")
elif a=='unown':
    print("50.unown")
    print("height:50.8 cm")
    print("weight:5 kg")
    print("psychic type pokemon")
    print("dosen't evolve")
elif a=='wobbuffet':
    print("51.wobbuffet")
    print("height:1.3 m")
    print("weight:28 kg")   
    print("psychic type pokemon")
    print("dosen't evolve")    
elif a=='girafaring':
    print("52.girafaring")
    print("height:1.5 m")
    print("weight:42 kg")
    print("psychic and normal type pokemon")
    print("dosen't evolve")
elif a=='pineco':
    print("53.pineco")
    print("height:61 cm")
    print("weight:7.2 kg")
    print("bug type pokemon")
    print("evolves to forretress")
elif a=='forretress':
    print("56.forretress")
    print("height:1.19 m")  
    print("weight:126 kg")
    print("steel and bug type pokemon")
    print("dosen't evolve")
elif a=='dunsparce':
    print("57.dunsparce")
    print("height:1.5 m")
    print("weight:14 kg")
    print("normal type pokemon")
    print("dosen't evolve")
elif a=='gilagar':
    print("58.gilagar")
    print("height:1.09 m")                  
    print("weight:65 kg")
    print("ground and flying type pokemon")
    print("evolves to gliscor")
elif a=='steelix':
    print("59.steelix")
    print("height:9.19 m")
    print("weight:400 kg")
    print("ground and rock type pokemon")
    print("dosen't evolve")
elif a=='snubbull':
    print("60.snubbull")
    print("height:61 cm")
    print("weight:7.8 kg")
    print("fairy type pokemon")
    print("evolves to granbull")
elif a=='scizor':
    print("61.scizor")
    print("height:1.8 m")
    print("weight:118 kg")
    print("bug and steel type pokemon")
    print("dosen't evolve")
elif a=='shuckle':
    print("62.shuckle")
    print("height:61 cm")
    print("weight:21 kg")
    print("bug and rock type pokemon")
    print("dosen't evolve")
elif a=='heracross':
    print("63.heracross")
    print("height:1.5 m")
    
    print("weight:54 kg")
    print("bug and fighting type pokemon")
    print("dosen't evolve")
elif a=='sneasel':
    print("64.sneasel")
    print("height:88.3 cm")
    print("weight:28 kg")
    print("ice and dark type pokemon")
    print("evolves to weavile")
elif a=='teddiursa':
    print("65.teddiursa")
    print("height:61 cm")
    print("weight:8.8 kg")
    print("normal type pokemon")
    print("evolves to Ursaring")
elif a=='ursaring':
    print("66.ursaring")
    print("height:1.8 m")
    print("weight:126 kg")
    print("normal type pokemon")
    print("dosen't evolve")
elif a=='slugma':
    print("67.slugma")
    print("height:71.1 cm")
    print("weight:35 kg")
    print("fire type pokemon")
    print("evolves to magcargo")
elif a=='magcargo':
    print("68.magcargo")
    print("height:78.7 cm")
    print("weight:55 kg")
    print("fire and onix type pokemon")
    print("dosen't evolve")
elif a=='swinub':
    print("69.swinub")
    print("height:40.6 cm")
    print("weight:6.5 kg")
    print("ice and ground type pokemon")
    print("evolves to piloswine")
elif a=='piloswine':
    print("70.piloswine")
    print("height:1.09 m")
    print("weight:56 kg")
    print("ice and ground type pokemon")
    print("evolves to mamoswine")
elif a=='corsola':
    print("71.corsola")
    print("height:61 cm",123)
    print("weight:5 kg")
    print("onix and water type pokemon")
    print("dosen't evolve")
elif a=='remoraid':
    print("72.remoraid")
    print("height:61 kg")
    print("weight:12 kg")
    print("water type pokemon")
    print("evolves to octillery")
elif a=='octillery':
    print("73.octillery")
    print("height:88.9 cm")
    print("weight:28 kg")
    print("water type pokemon")
    print("dosen't evolve")
elif a=='delibird':
    print("74.delibird")
    print("height:88.9 cm")
    print("weight:16 kg")
    print("icwe and flying type pokemon")
    print("dosen't evolve")    
elif a=='mantine':
    print("75.mantine")
    print("height:2.11 m")
    print("weight:220 kg")
    print("water and flying type pokemon")
    print("evolve dosen't")
elif a=='skarmory':
    print("76.skarmory")
    print("height:1.7 m")
    print("weight:50 kg")
    print("steel and fying type pokemon")
    print("dosen't evolve")
elif a=='houndour':
    print("77.houndour")
    print("height:61 cm")
    print("weight:11 kg")
    print("dark and fire type pokemon")
    print("evolves to houndoom")
elif a=='houndoom':
    print("78.houndoom")
    print("height:1.4 m")
    print("weight:35 kg")
    print("dark and fire type pokemon")
    print("dosen't evolve")
elif a=='kingdra':
    print("79.kingdra")
    print("height:1.8 m",ved)
    print("weight:152 kg")
    print("salamence and water type pokemon")
    print("evolves to seadra")
elif a=='phanpy':
    print("80.phanpy")
    print("height:50.8 cm")
    print("weight:34 kg")
    print("ground type pokemon")
    print("evolves to donphan")
elif a=='donphan':
    print("81.donphan")
    print("height:1.09m")
    print("weight:120 kg")
    print("ground type pokemon")
    print("dosen't evolve")
elif a=='porygon z':
    print("82.porygon z")
    print("height:88.9")
    print("weight:34 kg")
    print("normal type pokemon")
    print("dosen't evolve")    
elif a=='stantler':
    print("83.stantler")
    print("height:1.4 m")
    print("weight:71 kg")
    print("normal type pokemon")
    print("dosen't evolve")    
elif a=='smeargle':
    print("84.smeargle")
    print("height:1.19 m")
    print("weight:58 kg")
    print("normal type pokemon")
    print("dosen't evolve")
elif a=='tyrogue':
    print("85.tyrougue")
    print("height:71.1 cm")
    print("weight:21 kg")
    print("fighting type pokemon")
    print("evolves to any of : hitmontop, hitmonlee, hitmonchan")    
elif a=='hitmontop':    
    print("86.hitmontop")
    print("height:1.4 m")
    print("weight:48 kg",a)
    print("fighting type pokemon")
    print("dosen't evolve")
elif a=='smoochum':
    print("87.smoochum")
    print("height:40.6 cm")
    print("weight:6 kg")
    print("ice and psychic type pokemon")
    print("evolves to jynx")
elif a=='elekid':
    print("88.elekid")
    print("height:61 cm")
    print("weight:23 kg")
    print("electric type pokemon")
    print("evolves to electabuzz")
elif a=='magby':
    print("89.magby")
    print("height:71.1 cm")
    print("weight:21 kg")
    print("fire type pokemon")
    print("evolves to magmar")    
elif a=='miltank':
    print("90.miltank")
    print("height:1.19 m")
    print("weight:75 kg")
    print("normal type pokemon")
    print("dosen't evolve")    
elif a=='blissey':
    print("91.blissey")
    print("height:1.5 m")
    print("weight:47 kg")
    print("fairy type pokemon")
    print("dosen't evolve")    
elif a=='raikou':
    print("92.raikou")
    print("height:1.9 m")
    print("weight:178 kg")
    print("electric type pokemon")
    print("dosen't evolve")
elif a=='entei':
    print("93.entei")
    print("height:2.11 m")
    print("weight:198 kg")
    print("fire type pokemon")
    print("dosen't evolve")
elif a=='suicune':
    print("94.suicune")
    print("height:2.01 m")
    print("weight:187 kg")
    print("water type pokemon")
    print("dosen't evolve")    
elif a=='larvitar':
    print("95.larvitar")
    print("height:61 cm")
    print("weight:72 kg")
    print("ground and rock type pokemon")
    print("evolve to pupitar")
elif a=='pupitar':
    print("96.pupitar")
    print("height:1.19 m")
    print("weight:152 kg")
    print("ground and rock type pokemon")
    print("evolves to tyranitar")
elif a=='tyranitar':
    print("97.tyranitar")
    print("height:2.01 m")
    print("weight:202 kg")
    print("dark and rock type pokemon")
    print("dosen't evolve")
elif a=='lugia':
    print("98.lugia")
    print("height:5.21 m")
    print("weight:216 kg")
    print("psychic and flying type pokemon")
    print("dosen't evolve")
elif a=='ho-oh':
    print("99.ho-oh")
    print("height:3.18 m")
    print("weight:199 kg")
    print("fire and flying type pokemon")
    print("dosen't evolve")
elif a=='celebi':
    print("100.celebi")
    print("height:61 cm")
    print("weight:5 kg")
    print("grass and psychic type pokemon")
    print("dosen't evolve")
else:
    print("you overruled the condition!!")
    print("note:(1) pokemon's name should be in small letters")
    print("     (2) this poketab is restricted only till jhoto league")
    
b=str(input("if you want to continue enter 'c' or enter 'exit'"))
while b=='c':      
    print("note:(1) pokemon's name should be in small letters")
    print("     (2) this poketab is restricted only till jhoto league")
    a=str(input("enter the name of pokemon you wish to know about:"))
    print("info::")
    if a=='chikorita':
        print("1.chikorita")
        print("height:88.9cm")
        print("weight:6.4kg")
        print("grass type pokemon ")
        print(" evovles to:bayleef")
    elif a=='bayleef':
        print("2.bayleef")
        print("height:1.19m")
        print("weight:16kg")
        print("grass type pokemon")
        print("evolves to meganium")
    elif a=='meganium':
        print("3.megnium")
        print("height:1.8m")
        print("weght:100.5kg")
        print("grass type pokemon")
        print("dosen't evolve")
    elif a=='cyndaquill':
        print("4.cydaquill")
        print("height:50.8cm")
        print("weight:7.9kg")
        print("fire type pokemon")
        print("evolves to quillava")
    elif a=='quilava':
        print("5.quilava")
        print("height:88.9cm")
        print("weight:19kg")
        print("fire type pokemon")
        print("evovles to typhlosion")
    elif a=='typhlosion':
        print("6.typhosion")
        print("height:1.7m")
        print("weight:8kg")
        print("fire type pokemon")
        print("dosn't evovle")
    elif a=='totodile':
        print("7.totodile")
        print("height:61m")
        print("weight:9.5kg")
        print("water type pokemon")
        print("evolves to croconaw")
    elif a=='croconaw':
        print("8.croconaw")
        print("height:1.9m")
        print("weight:25kg")
        print("water type pokemon")
        print("evolves to feraligator")
    elif a=='feraligator':
        print("9.feraligator")
        print("height:2.31m")
        print("weight:89kg")
        print("water type pokemon")
        print("dosn't evolves")
    elif a=='senteret':
        print("10.senteret")
        print("height:78.7cm")
        print("weight:6kg")
        print("normal type pokemon")
        print("evolves to furret")
    elif a=='furret':
        print("11.furret")
        print("height:1.8m")
        print("weight:32kg")
        print("normal type pokemon")
        print("evolves to hoothoot")
    elif a=='hoothoot':
        print("12.hoothoot")
        print("height:71.1cm")
        print("weight:21kg")
        print("normal type pokemon")
        print("evolves to noctowl")
    elif a=='noctowl':
        print("13.noctowl")
        print("height:1.6 m")
        print("weight:41 kg")
        print("normal type pokemon")
        print("dosen't evolve")
    elif a=='ledyba':
        print("14.Ledyba")
        print("height:99.1 cm")
        print("weight:11 kg")
        print("bug and flying type pokemon")
        print("evolves to ledian")
    elif a=='ledian':
        print("15.Ledian")
        print("height:1.4 m")
        print("weight:36 kg ")
        print("bug and flying type pokemon")
        print(" dosen't evolve")
    elif a=='spinarak':
        print("16.Spinarak")
        print("height:50.8cm")
        print("weight:8.5 kg")
        print("bug and poison type pokemon")
        print("evolves to ariados")
    elif a=='ariados':
        print("17.Ariados")
        print("height:1.09 m")
        print("weight:34 kg")
        print("bug and poison type pokemon")
        print("dosen't evolve")
    elif a=='crobat':
        print("18.crobat")
        print("height:1.8 m")
        print("weight:75 kg")
        print("poison and flying type pokemon")
        print("dosen't evolve")
    elif a=='chinchou':
        print("19.Chinchou")
        print("height:50.8")
        print("weight:12 kg")
        print("electric and water type pokemon")
        print("evolves to lanturn")
    elif a=='lanturn':
        print("20. lanturn")
        print("height:1.2 m")
        print("weight:22.5 kg")
        print("electric and water type pokemon")
        print("dosen't evolve")
    elif a=='pichu':
        print("21.pichu")
        print("height:0.3m")
        print("weight:2 kg")
        print("electric type pokemon")
        print("evolves to pikachu")
    elif a=='cleffa':
        print("22.cleffa")
        print("height:0.3m")
        print("weight:3 kg")
        print("fairy type pokemon")
        print("evolves to clefairy")
    elif a=='igglybuff':
        print("23.igglybuff")
        print("height:0.3m")
        print("weight:1 kg")
        print("fairy and normal type pokemon")
        print("evolves to jigglypuff")
    elif a=='togepi':
        print("24.togepi")
        print("height:0.3m")
        print("weight:1kg")
        print("fairy type pokemon")
        print("evolves to togetic")
    elif a=='togetic':
        print("25.togetic")
        print("height:0.6 m")
        print("weight:3.2 kg")
        print("fairy and flying type pokemon")
        print("evolves to togekiss")
    elif a=='natu':
        print("26.natu")
        print("height:0.2 m")
        print("weight:2 kg")
        print("psichic and flying type pokemon")
        print("evolves to xatu ")
    elif a=='xatu':
        print("27.xatu")
        print("height:1.5 m")
        print("weight:15 kg")
        print("psychic and flying type pokemon")
        print("dosen't evolve")
    elif a=='mareep':
        print("28.mareep")
        print("height:0.6 m")
        print("weight:7.8 kg")
        print("electric type pokemon")
        print("evolves to flaffy")
    elif a=='flaafy':
        print("29.flaafy")
        print("height:78.7 cm")
        print("weight:13 kg")
        print("electric type pokemon")
        print("evolves to ampharos")
    elif a=='ampharos':
        print("30.ampharos")
        print("height:1.4 m")
        print("weight:61.5 kg ")
        print("electric type pokemon")
        print("dosen't evolve")
    elif a=='bellossom':
        print("31.bellossom")
        print("height:40.6 cm")
        print("weight:5.8 kg")
        print("grass type pokemon")
        print("dosen't evolve")
    elif a=='marill':
        print("32.marill")
        print("height:40.6 cm")
        print("weight:8.5 kg")
        print("water type pokemon")
        print("evolves to azumarill")
    elif a=='azumarill':
        print("33.azumarill")
        print("height:78.5 cm")
        print("weight:28 kg")
        print("water type pokemon")
        print("dosen't evolve")
    elif a=='politoed':
        print("34.politoed")
        print("height:1.09m")
        print("weight:34 kg")
        print("water type pokemon")
        print("dosen't evolve")
    elif a=='sudowoodo':
        print("35.sudowoodo")
        print("height:1.19 m")
        print("weight:38 kg")
        print("rock type pokemon")
        print("dosen't evolve")
    elif a=='hoppip':
        print("36.hoppip")
        print("height:40.6 cm")
        print("weight:499 g")
        print("flying and grass type pokemon")
        print("evolves to skiploom")
    elif a=='skiploom':
        print("37.skiploom")
        print("height:61 cm")
        print("weight:998 g")
        print("flying and grass type pokemon")
        print("evolves to jumpluff")
    elif a=='jumpluff':
        print("38.jumpluff")
        print("height:78.7 cm",a)
        print("weight:3 kg")
        print("flying and grass type pokemon")
        print("dosen't evolve")    
    elif a=='aipom':
        print("39.aipom")
        print("height:78.7")
        print("weight:12 kg ")
        print("normal type pokemon")
        print("evolves to ambipom")
    elif a=='sunkern':
        print("40.sunkern")
        print("height:30.5cm")
        print("weight:1.8 kg")
        print("grass type pokemon")
        print("evolves to sunflora")
    elif a=='sunflora':
        print("41.sunflora")
        print("height:78.7 cm")
        print("weight:8.5 kg")
        print("grass type pokemon")
        print("dosen't evolve")
    elif a=='yanma':
        print("42.yanma")
        print("height:1.19m")
        print("weight:38 kg")
        print("flying and bug type pokemon")
        print("evolves to yanmega")
    elif a=='wooper':
        print("43.wooper")
        print("height:40.6 cm ")
        print("weight:8.5 kg ")
        print("ground and water type pokemon")
        print("evolves to quagsire")
    elif a=='quagsire':
        print("44.quagsire")
        print("height:1.4 m")
        print("weight:75 kg")
        print("ground and water type pokemon")
        print("dosen't evolve")
    elif a=='espeon':
        print("45.espeon")
        print("height:88.9 cm")
        print("weight:26 kg")
        print("psychic type pokemon")
        print("dosen't evolve")
    elif a=='umbreon':
        print("46.umbreon")
        print("height:99.1 cm")
        print("weight:27 kg")
        print("dark type pokemon")
        print("dosen't evolve")
    elif a=='murkrow':
        print("47.murkrow")
        print("height:50.8 cm")
        print("weight:2.1 kg")
        print("dark and flying type pokemon")
        print("evolves to honchkrow")
    elif a=='slowking':
        print("48.slowking")
        print("height:2.01 m")
        print("weight:80 kg")
        print("psychic and water type pokemon")
        print("dosen't evolve")
    elif a=='misdreavus':
        print("49.misdreavus")
        print("height:71.1 cm")
        print("weight:998 g")
        print("ghost type pokemon")
        print("evolves to mismagius")
    elif a=='unown':
        print("50.unown")
        print("height:50.8 cm")
        print("weight:5 kg")
        print("psychic type pokemon")
        print("dosen't evolve")
    elif a=='wobbuffet':
        print("51.wobbuffet")
        print("height:1.3 m")
        print("weight:28 kg")
        print("psychic type pokemon")
        print("dosen't evolve")    
    elif a=='girafaring':
        print("52.girafaring")
        print("height:1.5 m")
        print("weight:42 kg")
        print("psychic and normal type pokemon")
        print("dosen't evolve")
    elif a=='pineco':
        print("53.pineco")
        print("height:61 cm")
        print("weight:7.2 kg")
        print("bug type pokemon")
        print("evolves to forretress")
    elif a=='forretress':
        print("56.forretress")
        print("height:1.19 m")
        print("weight:126 kg")
        print("steel and bug type pokemon")
        print("dosen't evolve")
    elif a=='dunsparce':
        print("57.dunsparce")
        print("height:1.5 m")
        print("weight:14 kg")
        print("normal type pokemon")
        print("dosen't evolve")
    elif a=='gilagar':
        print("58.gilagar")
        print("height:1.09 m")
        print("weight:65 kg")
        print("ground and flying type pokemon")
        print("evolves to gliscor")
    elif a=='steelix':
        print("59.steelix")
        print("height:9.19 m")
        print("weight:400 kg")
        print("ground and rock type pokemon")
        print("dosen't evolve")
    elif a=='snubbull':
        print("60.snubbull")
        print("height:61 cm")
        print("weight:7.8 kg")
        print("fairy type pokemon")
        print("evolves to granbull")
    elif a=='scizor':
        print("61.scizor")
        print("height:1.8 m")
        print("weight:118 kg")
        print("bug and steel type pokemon")
        print("dosen't evolve")
    elif a=='shuckle':
        print("62.shuckle")
        print("height:61 cm")
        print("weight:21 kg")
        print("bug and rock type pokemon")
        print("dosen't evolve")
    elif a=='heracross':
        print("63.heracross")
        print("height:1.5 m")
        print("weight:54 kg")
        print("bug and fighting type pokemon")
        print("dosen't evolve")
    elif a=='sneasel':
        print("64.sneasel")
        print("height:88.3 cm")
        print("weight:28 kg")
        print("ice and dark type pokemon")
        print("evolves to weavile")
    elif a=='teddiursa':
        print("65.teddiursa")
        print("height:61 cm")
        print("weight:8.8 kg")
        print("normal type pokemon")
        print("evolves to Ursaring")
    elif a=='ursaring':
        print("66.ursaring")
        print("height:1.8 m")
        print("weight:126 kg")
        print("normal type pokemon")
        print("dosen't evolve")
    elif a=='slugma':
        print("67.slugma")
        print("height:71.1 cm")
        print("weight:35 kg")
        print("fire type pokemon")
        print("evolves to magcargo")
    elif a=='magcargo':
        print("68.magcargo")
        print("height:78.7 cm")
        print("weight:55 kg")
        print("fire and onix type pokemon")
        print("dosen't evolve")
    elif a=='swinub':
        print("69.swinub")
        print("height:40.6 cm")
        print("weight:6.5 kg")
        print("ice and ground type pokemon")
        print("evolves to piloswine")
    elif a=='piloswine':
        print("70.piloswine")
        print("height:1.09 m")
        print("weight:56 kg")
        print("ice and ground type pokemon")
        print("evolves to mamoswine")
    elif a=='corsola':
        print("71.corsola")
        print("height:61 cm")
        print("weight:5 kg")
        print("onix and water type pokemon")
        print("dosen't evolve")
    elif a=='remoraid':
        print("72.remoraid")
        print("height:61 kg")
        print("weight:12 kg")
        print("water type pokemon")
        print("evolves to octillery")
    elif a=='octillery':
        print("73.octillery")
        print("height:88.9 cm")
        print("weight:28 kg")
        print("water type pokemon")
        print("dosen't evolve")
    elif a=='delibird':
        print("74.delibird")
        print("height:88.9 cm")
        print("weight:16 kg")
        print("icwe and flying type pokemon")
        print("dosen't evolve")    
    elif a=='mantine':
        print("75.mantine")
        print("height:2.11 m")
        print("weight:220 kg")
        print("water and flying type pokemon")
        print("evolve dosen't")
    elif a=='skarmory':
        print("76.skarmory")
        print("height:1.7 m")
        print("weight:50 kg")
        print("steel and fying type pokemon")
        print("dosen't evolve")
    elif a=='houndour':
        print("77.houndour")
        print("height:61 cm")
        print("weight:11 kg")
        print("dark and fire type pokemon")
        print("evolves to houndoom")
    elif a=='houndoom':
        print("78.houndoom")
        print("height:1.4 m")
        print("weight:35 kg")
        print("dark and fire type pokemon")
        print("dosen't evolve")
    elif a=='kingdra':
        print("79.kingdra")
        print("height:1.8 m")
        print("weight:152 kg")
        print("salamence and water type pokemon")
        print("evolves to seadra")
    elif a=='phanpy':
        print("80.phanpy")
        print("height:50.8 cm")
        print("weight:34 kg")
        print("ground type pokemon")
        print("evolves to donphan")
    elif a=='donphan':
        print("81.donphan")
        print("height:1.09m")
        print("weight:120 kg")
        print("ground type pokemon")
        print("dosen't evolve")
    elif a=='porygon z':
        print("82.porygon z")
        print("height:88.9")
        print("weight:34 kg")
        print("normal type pokemon")
        print("dosen't evolve")    
    elif a=='stantler':
        print("83.stantler")
        print("height:1.4 m")
        print("weight:71 kg")
        print("normal type pokemon")
        print("dosen't evolve")    
    elif a=='smeargle':
        print("84.smeargle")
        print("height:1.19 m")
        print("weight:58 kg")
        print("normal type pokemon")
        print("dosen't evolve")
    elif a=='tyrogue':
        print("85.tyrougue")
        print("height:71.1 cm")
        print("weight:21 kg")
        print("fighting type pokemon")
        print("evolves to any of : hitmontop, hitmonlee, hitmonchan")    
    elif a=='hitmontop':    
        print("86.hitmontop")
        print("height:1.4 m")
        print("weight:48 kg")
        print("fighting type pokemon")
        print("dosen't evolve")
    elif a=='smoochum':
        print("87.smoochum")
        print("height:40.6 cm")
        print("weight:6 kg")
        print("ice and psychic type pokemon")
        print("evolves to jynx")
    elif a=='elekid':
        print("88.elekid")
        print("height:61 cm")
        print("weight:23 kg")
        print("electric type pokemon")
        print("evolves to electabuzz")
    elif a=='magby':
        print("89.magby")
        print("height:71.1 cm")
        print("weight:21 kg")
        print("fire type pokemon")
        print("evolves to magmar")    
    elif a=='miltank':
        print("90.miltank")
        print("height:1.19 m")
        print("weight:75 kg")
        print("normal type pokemon")
        print("dosen't evolve")    
    elif a=='blissey':
        print("91.blissey")
        print("height:1.5 m")
        print("weight:47 kg")
        print("fairy type pokemon")
        print("dosen't evolve")    
    elif a=='raikou':
        print("92.raikou")
        print("height:1.9 m")
        print("weight:178 kg")
        print("electric type pokemon")
        print("dosen't evolve")
    elif a=='entei':
        print("93.entei")
        print("height:2.11 m")
        print("weight:198 kg")
        print("fire type pokemon")
        print("dosen't evolve")
    elif a=='suicune':
        print("94.suicune",a)
        print("height:2.01 m")
        print("weight:187 kg")
        print("water type pokemon")
        print("dosen't evolve")    
    elif a=='larvitar':
        print("95.larvitar")
        print("height:61 cm")
        print("weight:72 kg")
        print("ground and rock type pokemon")
        print("evolve to pupitar")
    elif a=='pupitar':
        print("height:1.19 m")
        print("weight:152 kg")
        print("ground and rock type pokemon")
        print("evolves to tyranitar")
    elif a=='tyranitar':
        print("97.tyranitar")
        print("height:2.01 m")
        print("weight:202 kg")
        print("dark and rock type pokemon")
        print("dosen't evolve")
    elif a=='lugia':
        print("98.lugia")
        print("height:5.21 m")
        print("weight:216 kg")
        print("psychic and flying type pokemon")
        print("dosen't evolve")
    elif a=='ho-oh':
        print("99.ho-oh")
        print("height:3.18 m")
        print("weight:199 kg")
        print("fire and flying type pokemon")
        print("dosen't evolve")
    elif a=='celebi':
        print("100.celebi")
        print("height:61 cm")
        print("weight:5 kg")
        print("grass and psychic type pokemon")
        print("dosen't evolve")
    else:
        print("you overruled the condition!!")
        print("note:(1) pokemon's name should be in small letters")
        print("     (2) this poketab is restricted only till jhoto league")
else:
    print("thank you")
    print("you may exit the calculator by presssing any key")
