import turtle
import pdb
t=turtle.Turtle()
t.shape("circle")
t.color("#fcc200")
t.shapesize(2)
e=turtle.Turtle()
t.shape("circle")
e.shape("circle")
e.shapesize(1)
t.shapesize(2)
e.penup()
e.color("#005ad6")
e.shape("circle")
e.rt(90)
e.fd(250)
e.lt(90)
e.pendown()
e.circle(250)
