import turtle
t=turtle.Turtle()  #import pdb 
turtle.bgcolor("grey")
t.color("black","black")
t.ht()
t.begin_fill()
t.circle(50,180)
t.circle(100,180)
t.rt(180)
t.circle(-50,180)
t.end_fill()
t.color("black","white")
t.begin_fill()
t.circle(50,180)
t.rt(180)
t.circle(-100,180)
t.circle(-50,180)
t.end_fill()
t.color("black","black")
t.rt(90)
t.penup()
t.fd(30)
t.lt(90)
t.pendown()
t.begin_fill()
t.circle(-20)
t.end_fill()
t.color("black","white")
t.penup()
t.lt(90)
t.fd(100)
t.lt(90)
t.pendown()
t.begin_fill()
t.circle(20)
t.end_fill()
t.penup()
t.rt(90)
t.fd(70)
t.rt(90)
t.write("yinyang",font=("Times new roman",19,"bold"))
t.fd(100)


